### ISSUE TITLE
The results of CleanNet in THUMOS at IoU 0.1 and 0.2 are not referred in the paper.

### ISSUE THREAD

**Issue by fjchange** [Alvin-Zeng/Awesome-Temporal-Action-Localization#11]
The results of CleanNet in THUMOS at IoU 0.1 and 0.2 are not referred in the paper. 
I have checked the iccv 19 paper and corresponding supplement material, but no this record.

**Comment by bolixinyu** [comment]
Thanks for your reminder, we have updated it with the results reported in the paper.
