### ISSUE TITLE
AAAI2020 paper

### ISSUE THREAD

**Issue by swordlidev** [Alvin-Zeng/Awesome-Temporal-Action-Localization#2]
Fast Learning of Temporal Action Proposal via Dense Boundary Generator
https://arxiv.org/abs/1911.04127
DBG is also awesome

**Comment by Alvin-Zeng** [comment]
Thank you for your kind reminding! We have updated DBG.

**Comment by linchuming** [comment]
Hi, @Alvin-Zeng ,  the short name of DBG paper is wrong (you mark the name as G-TAD). Could you change the name to DBG?
