### ISSUE TITLE
ICLR paper MAAN 

### ISSUE THREAD

**Issue by XiSHEN0220** [Alvin-Zeng/Awesome-Temporal-Action-Localization#4]
Hi, thanks for collecting related papers in this domain!!

Could you please add the paper '[Marginalized Average Attentional Network for Weakly-Supervised Learning](https://openreview.net/forum?id=HkljioCcFQ)' ? 

It was accepted by ICLR 2019.

**Comment by Alvin-Zeng** [comment]
Hi, please make a pull request.
